workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - browserstack_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.sample.browserstack"
      node: 15.13.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android Test release
        script: |
          cd android && ./gradlew assembleAndroidTest
      - name: Build Android release
        script: |
          # Set environment variable so it can be used to increment build number in android/app/build.gradle
          # export NEW_BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=alpha) + 1))             

          export NEW_BUILD_NUMBER=$(($(firebase-app-distribution get-latest-build-number --package-name "$PACKAGE_NAME") + 1))
          cd android && ./gradlew assembleRelease
      - name: BrowserStack upload
        script: |      
            APP_URL=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN" \
              -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
              -F "file=@android/app/build/outputs/apk/release/app-release.apk" \
              | jq -r '.app_url')

            TEST_URL=$(curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN" \
              -X POST "https://api-cloud.browserstack.com/app-automate/espresso/test-suite" \
              -F "file=@android/app/build/outputs/apk/androidTest/release/app-release-androidTest.apk" \
              | jq -r '.test_url')

            curl -X POST "https://api-cloud.browserstack.com/app-automate/espresso/build" \
              -d '{"devices": ["Google Pixel 3-9.0"], "app": "'"$APP_URL"'",
                 "deviceLogs" : true, "testSuite": "'"$TEST_URL"'"}' \
              -H "Content-Type: application/json" \
              -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_TOKEN"    
    artifacts:
        - android/app/build/outputs/**/*.apk
