workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    cache:
      cache_paths:
        - ~/.sonar
    environment:
      android_signing:
        - codemagic_keystore
      groups:
        - sonarcloud_credentials
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - name: Set up local properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"      
      - name: Build Android app
        script: |
          ./gradlew assembleRelease
      - name: Generate and upload code analysis report
        script: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.host.url=$SONARQUBE_URL \
            -Dsonar.login=$SONAR_TOKEN
    artifacts:
      - app/build/outputs/**/**/*.apk
    publishing:
      email:
        recipients:
          - user@email.com
      slack:
        channel: '#testing'
        notify_on_build_start: true # To receive a notification when a build starts
        notify:
          success: true # To not receive a notification when a build succeeds
          failure: false 
